#!/bin/bash

# Path to config.sh
config_file="config.sh"

# Source config.sh
source "$config_file"

#add user
adduser $username

# Add user to sudo group
usermod -aG wheel "$username"

echo "$username:$password" | /usr/sbin/chpasswd -c SHA512
